name: module3_task1
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  module3_task0:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: cd in to correct directory
        run: |
          cd module3_task1
          make help
      -name: cp in to directory
       run:
         cp module3_task1
         make help
