name: module3_task0
on:
 push:
 branches:
   -main
 schedule:
   -cron:"0 0 * * *"
 jobs:
  module3-task0:
   -name: Checkout
   uses: cd in to correct directory
   run:
    cd module3_task0
    make help
