name: module3_task0
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
  pull-request: 
    branches: master
  push:
    branches-ignore: master
on: [push]
  pull-request: 
    branches: master
  push:
    branches-ignore: master
    
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
