name: module3_task0
on:
 push:
  branches:
 schedule:
  - cron: "0 0 * * *"
jobs:
 module3_task0:
  runs-ubuntu-latest
  steps:
   -name: Checkout
    user: actions/checkout@v3
   -name: cd in to correct directory
    run:
     cd module3_task0
     make help
